# Generated by Django 3.2.12 on 2023-09-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=25)),
                ('size', models.IntegerField()),
                ('colorway', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=200)),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
