# Generated by Django 3.2.12 on 2023-09-18 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20230918_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 21, 3, 47, 503062, tzinfo=utc)),
        ),
    ]
