# Generated by Django 4.2.5 on 2023-09-18 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_review_user_alter_bid_date_alter_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 23, 0, 48, 710119)),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 23, 0, 48, 709207, tzinfo=datetime.timezone.utc)),
        ),
    ]
