# Generated by Django 4.2.5 on 2023-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='shoe_photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
