# Generated by Django 3.2.12 on 2023-09-20 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_shoe_shoe_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='shoe',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
